services:
  owncast:
    image: owncast/owncast:latest
    container_name: owncast
    restart: always
    volumes:
      # 沿用你的绝对路径存储数据
      - /root/data/docker_data/owncast/data:/app/data
      # 内存盘：Owncast 往这里写
      - /dev/shm/owncast_hls:/app/data/hls
    networks:
      - owncast-net

  nginx:
    # 使用你刚刚推送成功的镜像
    image: seanmini/nginx-owncast-300p:v1
    container_name: owncast-nginx
    user: "0:0"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "80:80"
    volumes:
      # 唯一需要的挂载：Nginx 从这里读（只读模式）
      - /dev/shm/owncast_hls:/usr/share/nginx/html/hls:ro
      # 临时挂载宿主机的配置文件，它会覆盖镜像内部的 /etc/nginx/nginx.conf
      #- /root/data/docker_data/owncast/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - owncast
    networks:
      - owncast-net

networks:
  owncast-net:
    driver: bridge
