services:
  owncast:
    image: owncast/owncast:latest
    container_name: owncast
    restart: always
    ports:
      - "1935:1935"
    volumes:
      - ./data:/app/data
      - /dev/shm/owncast_hls:/app/data/hls
    networks:
      - owncast-net

  nginx:
    image: nginx:alpine
    container_name: owncast-nginx
    # 强制以 Root 身份运行，解决所有权限导致的 403 问题
    user: "0:0"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "80:80"
    volumes:
      # 确保你已经删除了 nginx.conf 里的 "user root;" 这一行
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /dev/shm/owncast_hls:/usr/share/nginx/html/hls:ro
    depends_on:
      - owncast
    networks:
      - owncast-net

networks:
  owncast-net:
    driver: bridge
root@pc-00868:~/dat
